// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ColorDatabaseGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageIdString = "a3830d63-1920-46ea-8b30-d11553b499c6";
        public static Guid PackageId = new Guid(PackageIdString);

        public const string CmdSetIdString = "df53d37b-40f2-4d21-be65-3c00efe5eb0f";
        public static Guid CmdSetId = new Guid(CmdSetIdString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GrabDarkThemeColorsCommandId = 0x0100;
        public const int GrabLightThemeColorsCommandId = 0x0200;
        public const int GrabBlueThemeColorsCommandId = 0x0300;
        public const int CopyThemeColorsToClipboardCommandId = 0x0400;
    }
}