// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ColorDatabaseGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "ColorDatabaseGenerator.e78839c0-43e0-49e1-9307-b867a373afeb";
        public const string Name = "ColorDatabaseGenerator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Robert Hofmann";
        public const string Tags = "";
    }
}
